### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by kdhly** [Jace-Tech/ChatGTP-clone#1]
npm run dev

> backend@1.0.0 dev
> nodemon src/server.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/server.ts`
D:\AServer\ChatGTP-clone\backend\node_modules\mongoose\lib\connection.js:695
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (D:\AServer\ChatGTP-clone\backend\node_modules\mongoose\lib\connection.js:695:11)
    at D:\AServer\ChatGTP-clone\backend\node_modules\mongoose\lib\index.js:411:10
    at D:\AServer\ChatGTP-clone\backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\AServer\ChatGTP-clone\backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (D:\AServer\ChatGTP-clone\backend\node_modules\mongoose\lib\index.js:1285:10)
    at Mongoose.connect (D:\AServer\ChatGTP-clone\backend\node_modules\mongoose\lib\index.js:410:20)
    at D:\AServer\ChatGTP-clone\backend\src\config\database.ts:7:18
    at Generator.next (<anonymous>)
    at D:\AServer\ChatGTP-clone\backend\src\config\database.ts:8:71
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Jace-Tech** [comment]
To fix this, you need to create a `.env` file in the root folder and then add these fields there.

```bash
API_KEY=Your_Open_AI_Secret_Key
MONGO_URL=Your_Mongo_DB_Connection_String
```

**Comment by Apoil** [comment]
I created a '.env' file under \ChatGTP-clone, USES the Open_AI_Secret_Key mongo_url using local mongo: / / localhost: 27017, he is still an error, which side is my wrong?

> To fix this, you need to create a `.env` file in the root folder and then add these fields there.
> 
> ```shell
> API_KEY=Your_Open_AI_Secret_Key
> MONGO_URL=Your_Mongo_DB_Connection_String
> ```

I created a '.env' file under \ChatGTP-clone, USES the Open_AI_Secret_Key mongo_url using local mongo: / / localhost: 27017, he is still an error, which side is my wrong?

**Comment by Jace-Tech** [comment]
I've updated the repo, clone it again
Sorry for the late response, I've been really busy

**Comment by Jace-Tech** [comment]
> To fix this, you need to create a `.env` file in the root folder and then add these fields there.
> 
> ```shell
> API_KEY=Your_Open_AI_Secret_Key
> MONGO_URL=Your_Mongo_DB_Connection_String
> ```
You can now remove the MONGO_URL from the `.env` file.
The reason for the whole issue was that I had two project that as making use of the backend server, but I've seperated them now. The `backend` folder only contains codes that are related to the CHAT BOT now.

**Comment by Apoil** [comment]
> > 要解决此问题，您需要在根文件夹中创建一个文件，然后在其中添加这些字段。`.env`
> > ```shell
> > API_KEY=Your_Open_AI_Secret_Key
> > MONGO_URL=Your_Mongo_DB_Connection_String
> > ```
> 
> 您现在可以从文件中删除MONGO_URL。整个问题的原因是我有两个项目使用后端服务器，但现在我已经将它们分开了。该文件夹现在仅包含与聊天 BOT 相关的代码。`.env``backend`

Ok thanks

**Comment by Apoil** [comment]
> > To fix this, you need to create a `.env` file in the root folder and then add these fields there.
> > ```shell
> > API_KEY=Your_Open_AI_Secret_Key
> > MONGO_URL=Your_Mongo_DB_Connection_String
> > ```
> 
> You can now remove the MONGO_URL from the `.env` file. The reason for the whole issue was that I had two project that as making use of the backend server, but I've seperated them now. The `backend` folder only contains codes that are related to the CHAT BOT now.

OK，thanks
